[providers]
python = "*"

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'Build phase complete'"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"